server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/usuarios
    username: postgres
    password: postgrespwd123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db.migration

jwt:
  secret: "EstaEsUnaClaveSuperSecretaDeAlMenos32Chars!!"
  expiration: 3600000


appDescription: "Pragma Powerup"
appVersion: "1.0.0"
