server:
  port: 8081
services:
  plazoleta:
    base-url: http://localhost:8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/usuarios
    username: postgres
    password: postgrespwd123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db.migration

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration



jwt:
  secret: "EstaEsUnaClaveSuperSecretaDeAlMenos32Chars!!"
  expiration: 3600000

logging:
  level:
    org.springframework.security: DEBUG

appDescription: "Pragma Powerup"
appVersion: "1.0.0"
